export const CATALOG_ITEMS_RECIEVED_COUNT = 'CATALOG_ITEMS_RECIEVED_COUNT';
export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';
