export const ORDER_SET_PHONE = 'ORDER_SET_PHONE';
export const ORDER_SET_ADDRESS = 'ORDER_SET_ADDRESS';
export const ORDER_SUBMIT_REQUEST = 'ORDER_SUBMIT_REQUEST';
export const ORDER_SUBMIT_FAILURE = 'ORDER_SUBMIT_FAILURE';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_RESET = 'ORDER_RESET';
