export const CATALOG_ITEM_SET_QUANTITY = 'CATALOG_ITEM_SET_QUANTITY';
export const CATALOG_ITEM_SELECT_SIZE = 'CATALOG_ITEM_SELECT_SIZE';
export const CATALOG_ITEM_REQUEST = 'CATALOG_ITEM_REQUEST';
export const CATALOG_ITEM_FAILURE = 'CATALOG_ITEM_FAILURE';
export const CATALOG_ITEM_SUCCESS = 'CATALOG_ITEM_SUCCESS';
